<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
    <!ELEMENT students (student+)>
    <!ELEMENT student (name, address+, phone, website)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ATTLIST address type (permanent | temporary) #REQUIRED>
    <!ELEMENT phone (#PCDATA)>
    <!ELEMENT website (#PCDATA)>
    <!ENTITY % phone "(\d{10})">
    <!NOTATION phone SYSTEM "urn:uuid:phone">
]>
<students>
    <student>
        <name>Aayush</name>
        <address type="permanent">Itahari-9 , sunsari, IL</address>
        <phone>123456789</phone>
        <website>http:w3school.com</website>
    </student>
    <student>
        <name>Ram</name>
       
        <phone>9876543210</phone>
        <website>http://Ram.com</website>
    </student>
</students>