=== Aayushstha1/XML-JSON/syudents.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, address+, phone, website)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST address
    type (permanent | temporary) #REQUIRED>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT website (#PCDATA)>

<!ENTITY % phone "([0-9]{10})">
<!ELEMENT phone (#PCDATA)>

=== Aayushstha1/XML-JSON/student.xml
<!DOCTYPE students SYSTEM "syudents.dtd">

<student>
    <name>Aayush </name>
    <address type="pernament">damak, jhapa</address>
    <phone>9824099712</phone>
    <website>http://www. w3school.com</website>

</student>
<student>
    <name>RAM </name>
   
    <phone>9824000000</phone>

</student>
