=== Aayushstha1/XML-JSON/TU.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="TU">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Post">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="5"/>
                                        <xs:maxLength value="8"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Salary">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="25000"/>
                                        <xs:maxInclusive value="50000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Gender">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="male"/>
                                        <xs:enumeration value="female"/>
                                        <xs:enumeration value="other"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Username">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="8"/>
                                    </xs:restriction>    
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Password">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z][A-Za-z0-9]{8}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Aayushstha1/XML-JSON/TU.xml
<?xml version="1.0" encoding="UTF-8"?>
<TU xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="TU.xsd">
    <Employee>
        <Post>Manager</Post>
        <Salary>30000</Salary>
        <Gender>male</Gender>
        <Username>john</Username>
        <Password>123456</Password>
    </Employee>
    <Employee>
        <Post>Engineer</Post>
        <Salary>45000</Salary>
        <Gender>male</Gender>
        <Username>Aayush</Username>
        <Password>987654</Password>
    </Employee>
</TU>
